[WIP] Collecticons V4
developmentseed/collecticons-processor pull request #19
Opened 2019-01-29 11:13 UTC by danielfdsilva

Changelog:

2019-01-29 13:07 UTC, danielfdsilva commented
Fix #8

2019-01-30 11:33 UTC, vgeorge requested changes
Tests are passing locally and I could generate a debug bundle successfully. Added some minor changes, mostly fixing typos.

Seems DEVELOPMENT.md isn't linked anywhere, I suggest to delete it as there are testing instructions at the README.

2019-01-30 11:33 UTC, vgeorge commented on src/utils.js
> + * Validates that the given path is a directory, throwing user erros
```suggestion
 * Validates that the given path is a directory, throwing user errors
```

2019-01-30 11:33 UTC, vgeorge commented on src/utils.js
> + * Validates that the given path is a directory, throwing user erros
```suggestion
 * Validates that the given path is a directory, throwing user errors
```

2019-01-30 11:33 UTC, vgeorge commented on src/core/bundle.js
> + * @param {objec} params
```suggestion
 * @param {object} params
```

2019-01-30 11:33 UTC, vgeorge commented on src/core/compile.js
> +  // noFileOutput: undefiend by default
```suggestion
  // noFileOutput: undefined by default
```

2019-01-30 11:33 UTC, vgeorge commented on .gitignore
> +test-run
```suggestion
test-run
collecticons.zip
collecticons/*
```

2019-01-30 11:33 UTC, vgeorge commented on .gitignore
> +test-run
Ignore bundle.

2019-02-02 12:28 UTC, merged